name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-netlify:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  deploy-vercel:
    needs: deploy-netlify
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit
