name: Deploy on push

on:
  push:
    branches:
      - master

jobs:
  deploy-netlify:
    uses: ./.github/workflows/deploy-netlify.yml
    secrets: inherit

  deploy-vercel:
    needs: deploy-netlify
    uses: ./.github/workflows/deploy-vercel.yml
    secrets: inherit

  # deploy-aws:
  #   needs: deploy-vercel
  #   uses: ./.github/workflows/deploy-aws.yml
  #   secrets: inherit
